### ISSUE TITLE
nodejs dictionary minor CR and some notes

### ISSUE THREAD

**Issue by solyarisoftware** [skywind3000/vim-dict#2]
Thanks Lin, 
for this plugin!

I just submitted a minor pull request: https://github.com/skywind3000/vim-dict/pull/1

Here some questions/proposals/notes:

* Possible README update
To be more explicit on usage, I'd suggest to insert in the README the necessary statement to put in .vimrc:

```
"k=uses dictionary, i=uses current and included files, t=tag completion. 
set complete=k,.
```

BTW, I realized it with command:

`:verbose set complete? dictionary?
`

And I finally set

`set complete=.,w,b,u,t,i,k
`

* Suggestion for NodeJS developers
I see that javascript and node are distinct set so I'd suggest:

`let g:vim_dict_config = {'javascript':'javascript,node'}
`

* Question: There are a lot of words duplicates in dictionary files: is that ok?

* Question: What the difference between dict.text and dict.word ? 

Thanks again
giorgio

**Comment by skywind3000** [comment]
Thanks, PR got merged. And I am going to update README according to your suggestion.

Q1: words duplication doesn't matter.

Q2: did you mean text.dict and word.dict ??

- word.dict: google 10K word list, excluding aggressive words.
- text.dict: 40K word list: google10k + COCA corpus + NBC corpus wordlist.

Suggest to use vim-dict with :
https://github.com/skywind3000/vim-auto-popmenu/

**Comment by solyarisoftware** [comment]
Thanks for your feedbacks! 
Yes I try asap vim-auto-popmenu. 
Regards
